### PR TITLE
Fixes #18: Table not generate

### LINKED ISSUE #18: Table not generate
i have problem with a table on my ebook
Screenshot from 2020-11-15 17-01-36

### PR DESCRIPTION
**Pull request by tarekdj**
This PR adds Table extension which enables the support for markdown tables.

### CODE REVIEW

**Comment by themsaid** [comment]
Can you share a screenshot of the table inside the PDF?

**Comment by tarekdj** [comment]
Sure!
image

Well! it's a raw table without any style.

**Comment by tarekdj** [comment]
@themsaid I updated the PR as following:

image

and

image

**Comment by themsaid** [comment]
thanks :)

**Pull request merged**
