### PR TITLE
Upgrade PHP 8.2 and packages

### PR DESCRIPTION
**Pull request by roberto-butti**
- upgrade and check with PHP 8.2
- upgrade code using new renderer of Commonmark
- upgrade GitHub Actions workflow
- using Pint with PSR12
- added configuration for cover image (instead of using hardcoded cover.jpg, you can specify a new file name and format, for example, my-cover.png)

### CODE REVIEW

**Comment by dcblogdev** [comment]
would be great to get this merged.

**Comment by edwinheij** [comment]
Can this be merged?

**Comment by edwinheij** [comment]
> * upgrade and check with PHP 8.2
> * upgrade code using new renderer of Commonmark
> * upgrade GitHub Actions workflow
> * using Pint with PSR12
> * added configuration for cover image (instead of using hardcoded cover.jpg, you can specify a new file name and format, for example, my-cover.png)

And adds support for Laravel v10

**Review by bobbyiliev — APPROVED** [review]
Looks good! Will be nice to get this merged 🙌

**Comment by sajaddp** [comment]
@themsaid Can you please merge it?

**Comment by roberto-butti** [comment]
Good morning Mohamed @themsaid .
I know you are super busy, and this project is great and very helpful.
I would like to know if you have any plans to upgrade this wonderful project with the latest packages.
I would like to understand how I can be of support or help (if necessary) in the maintenance of this project.

Thank you! 🙏 

Roberto

**Comment by bobbyiliev** [comment]
> Good morning Mohamed @themsaid . I know you are super busy, and this project is great and very helpful. I would like to know if you have any plans to upgrade this wonderful project with the latest packages. I would like to understand how I can be of support or help (if necessary) in the maintenance of this project.
> 
> Thank you! 🙏
> 
> Roberto

I would love to offer my help as well! I love the tool, it has allowed me to [publish 5+ books ](https://leanpub.com/u/bobbyiliev) so far 🙏 

image

**Comment by dcblogdev** [comment]
@roberto-butti can you release your fork? It would be amazing to have an installable version.

**Comment by hamidafghan** [comment]
@themsaid Any plan to have a quick review of this PR and merge. Thanks

**Comment by tnylea** [comment]
In case someone wants to use the version that @roberto-butti 

I've added a temporary working version here: https://github.com/thedevdojo/ibis

You can install with: `composer global require thedevdojo/ibis`

I will remove this package when it's no longer necessary and this gets merged in, but until then, you can use this version with the latest version of Laravel 😉

**Comment by hamidafghan** [comment]
Thank you @tnylea, Let's hope @themsaid sees the comments and merges the PR. :)

**Comment by roberto-butti** [comment]
Hi Folks, on top of this PR, i created the PHP8.3 Pull request.
Based on the PHP 8.2 changes, PHP 8.3 doesn't introduce changes; just adjusted the GitHub Workflow for the CI just to check the PHP8.3 execution
https://github.com/themsaid/ibis/pull/58

**Pull request merged**
